name: Templates - CI Build and Push to Container Registry

on:
  workflow_call:
    inputs:
      image_repo: { type: string, required: true } # e.g., ghcr.io/orchida-tax/peppol_ap
      push_convenience: { type: boolean, default: true } # alpha/latest/semver aliases

    outputs:
      sha7:
        description: "short SHA (7)"
        value: ${{ jobs.build.outputs.sha7 }}
      sha_tag:
        description: "image ref ghcr.io/...:sha-<sha7>"
        value: ${{ jobs.build.outputs.sha_tag }}
    secrets: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      sha7: ${{ steps.vars.outputs.sha7 }}
      sha_tag: ${{ steps.vars.outputs.sha_tag }} # ghcr.io/...:sha-<sha7>
    steps:
      - uses: actions/checkout@v4

      - name: Compute vars
        id: vars
        shell: bash
        run: |
          SHA7="$(echo $GITHUB_SHA | cut -c1-7)"
          echo "sha7=$SHA7" >> $GITHUB_OUTPUT
          echo "sha_tag=${{ inputs.image_repo }}:sha-${SHA7}" >> $GITHUB_OUTPUT
          [[ "${GITHUB_REF}" == "refs/heads/dev" ]] && echo "is_dev=true" >> $GITHUB_OUTPUT
          [[ "${GITHUB_REF}" == "refs/heads/alpha" ]] && echo "is_alpha=true" >> $GITHUB_OUTPUT
          [[ "${GITHUB_REF}" == "refs/heads/main"  ]] && echo "is_main=true"  >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
            echo "semver=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push immutable
        shell: bash
        run: |
          docker build -t "${{ steps.vars.outputs.sha_tag }}" .
          docker push "${{ steps.vars.outputs.sha_tag }}"

      - name: Push convenience tags (alpha/latest/semver)
        if: ${{ inputs.push_convenience }}
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ steps.vars.outputs.sha_tag }}"            # ghcr.io/...:sha-<sha7> (already pushed)
          IMAGE="${{ inputs.image_repo }}"
          SHA7="${{ steps.vars.outputs.sha7 }}"

          if [[ "${{ steps.vars.outputs.is_dev }}" == "true" ]]; then
            docker tag "$BASE" "${IMAGE}:dev"
            docker tag "$BASE" "${IMAGE}:dev-${SHA7}"
            docker push "${IMAGE}:dev"
            docker push "${IMAGE}:dev-${SHA7}"
          fi

          if [[ "${{ steps.vars.outputs.is_alpha }}" == "true" ]]; then
            docker tag "$BASE" "${IMAGE}:alpha"
            docker tag "$BASE" "${IMAGE}:alpha-${SHA7}"
            docker push "${IMAGE}:alpha"
            docker push "${IMAGE}:alpha-${SHA7}"
          fi

          if [[ "${{ steps.vars.outputs.is_main }}" == "true" ]]; then
            docker tag "$BASE" "${IMAGE}:latest"
            docker push "${IMAGE}:latest"
          fi

          if [[ "${{ steps.vars.outputs.is_release }}" == "true" ]]; then
            docker tag "$BASE" "${IMAGE}:${{ steps.vars.outputs.semver }}"
            docker push "${IMAGE}:${{ steps.vars.outputs.semver }}"
          fi
