name: "Build and Push Docker Image"
description: "Builds a Docker image, pushes it to GHCR, and outputs tags."
author: "Orchida Tax"

inputs:
    image_repo:
        description: "Target image repo, e.g. ghcr.io/orchida-tax/peppol_ap"
        required: true
    push_convenience:
        description: "Whether to push convenience tags (dev-latest, alpha-latest, semver, etc.)"
        required: false
        default: "true"

outputs:
    image_tag:
        description: "Immutable image tag (sha-<full_sha>)"
        value: ${{ steps.vars.outputs.image_tag }}
    is_tag_release:
        description: "true if the ref is a semver tag (vX.Y.Z)"
        value: ${{ steps.vars.outputs.is_tag_release }}
    semver:
        description: "SemVer tag (e.g., v1.2.3) if this is a tag release"
        value: ${{ steps.vars.outputs.semver }}

runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute vars
        id: vars
        shell: bash
        run: |
            set -euo pipefail

            short_sha="$(echo "$GITHUB_SHA" | cut -c1-7)"
            echo "short_sha=$short_sha"        >> "$GITHUB_OUTPUT"
            echo "full_sha=$GITHUB_SHA"        >> "$GITHUB_OUTPUT"
            echo "image_tag=sha-$GITHUB_SHA"   >> "$GITHUB_OUTPUT"

            [[ "${GITHUB_REF}" == "refs/heads/dev"   ]] && echo "is_dev=true"   >> "$GITHUB_OUTPUT"
            [[ "${GITHUB_REF}" == "refs/heads/alpha" ]] && echo "is_alpha=true" >> "$GITHUB_OUTPUT"
            [[ "${GITHUB_REF}" == "refs/heads/main"  ]] && echo "is_main=true"  >> "$GITHUB_OUTPUT"

            if [[ "${GITHUB_REF}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "is_tag_release=true"            >> "$GITHUB_OUTPUT"
              echo "semver=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
            fi

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ github.token }}

      - name: Build & push immutable
        shell: bash
        run: |
            set -euo pipefail

            IMAGE="${{ inputs.image_repo }}"
            full_sha="${{ steps.vars.outputs.full_sha }}"

            docker build -t "${IMAGE}:sha-${full_sha}" .
            docker push "${IMAGE}:sha-${full_sha}"

      - name: Push convenience tags (alpha/latest/semver)
        if: ${{ inputs.push_convenience == 'true' }}
        shell: bash
        run: |
            set -euo pipefail

            IMAGE="${{ inputs.image_repo }}"
            short_sha="${{ steps.vars.outputs.short_sha }}"
            full_sha="${{ steps.vars.outputs.full_sha }}"
            BASE="${IMAGE}:sha-${full_sha}"

            if [[ "${{ steps.vars.outputs.is_dev }}" == "true" ]]; then
              docker tag "$BASE" "${IMAGE}:dev-latest"
              docker tag "$BASE" "${IMAGE}:dev-${short_sha}"
              docker push "${IMAGE}:dev-latest"
              docker push "${IMAGE}:dev-${short_sha}"
            fi

            if [[ "${{ steps.vars.outputs.is_alpha }}" == "true" ]]; then
              docker tag "$BASE" "${IMAGE}:alpha-latest"
              docker tag "$BASE" "${IMAGE}:alpha-${short_sha}"
              docker push "${IMAGE}:alpha-latest"
              docker push "${IMAGE}:alpha-${short_sha}"
            fi

            if [[ "${{ steps.vars.outputs.is_main }}" == "true" ]]; then
              docker tag "$BASE" "${IMAGE}:latest"
              docker push "${IMAGE}:latest"
            fi

            if [[ "${{ steps.vars.outputs.is_tag_release }}" == "true" ]]; then
              docker tag "$BASE" "${IMAGE}:${{ steps.vars.outputs.semver }}"
              docker push "${IMAGE}:${{ steps.vars.outputs.semver }}"
            fi
